version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    #volumes:
    #  - ./backend:/app
    environment:
      - API_V1_STR=/api
      - PROJECT_NAME=Multi-Agent Collaborative AI Chat Platform
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
      - DEFAULT_AGENT_COUNT=3
      - A2A_DISCUSSION_ROUNDS=2
      - MAX_CONTEXT_DOCUMENTS=5
      - AUTH_ENABLED=false
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    #volumes:
    #  - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
